# Generated by Django 5.1.4 on 2025-03-31 12:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_code', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=30)),
                ('leader_name', models.CharField(max_length=30)),
                ('wh_leader', models.CharField(max_length=30)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, unique=True)),
                ('remain_quantity', models.IntegerField(default=0)),
                ('inventory_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('damage_date', models.DateField(default=django.utils.timezone.now)),
                ('maint_date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.TextField(default=None)),
                ('delivered_by', models.CharField(default=None, max_length=30)),
                ('received_by', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('event_code', models.CharField(default=None, max_length=30)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Good', 'Good'), ('Failed', 'Failed')], default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('add', 'add'), ('recovery', 'recovery')], default='add', max_length=10)),
                ('event_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smc_slt_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Dynamic Microphones', 'Dynamic Microphones'), ('Condencer', 'Condencer'), ('Wireless Kit', 'Wireless Kit'), ('Power Cable', 'Power Cable'), ('Electric Cable', 'Electric Cable'), ('A 56 D', 'A 56 D'), ('Signal Cables', 'Signal Cables'), ('Drum Kit', 'Drum Kit'), ('Accessories', 'Accessories'), ('Tools', 'Tools'), ('speaker', 'speaker'), ('mixer', 'mixer'), ('speaker', 'speaker'), ('stands', 'stands'), ('Equipment', 'Equipment'), ('Par light', 'Par light'), ('Par led', 'Par led'), ('Light', 'Light'), ('Dimmer Packs', 'Dimmer Packs')], max_length=30)),
                ('amount_of_events', models.IntegerField(default=0)),
                ('pack_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smc_slt_app.package')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smc_slt_app.inventory')),
            ],
        ),
    ]
